### ISSUE TITLE
balances combing XLM balances view for multiple accounts

### ISSUE THREAD

**Issue by MikeFair** [celrenheit/alfred#4]
I'm not sure if this was intentional or not, I don't think it was:
```
+---------+----------+---------------+
| openach | USD      |     0.0000000 |
+         +----------+---------------+
|         | XLM      |  9999.9998600 |
+---------+          +---------------+
| issuer  |          | 10019.9999200 |
+---------+----------+---------------+
```
"openach" and "issuer" are two separate accounts; issuer only has an XLM balance, but the XLM column isn't showing the separation and repeating the asset_code to show crossing an account level boundary.

**Comment by celrenheit** [comment]
This intended however this can be confusing.
I have changed it to look like this:
```
+----------------------+----------+---------------+
|        WALLET        | CURRENCY |    BALANCE    |
+----------------------+----------+---------------+
| main (GA5OM...TQGGY) | CNY      |    20.0000001 |
+----------------------+----------+---------------+
|                      | XLM      |  9983.3333033 |
+----------------------+----------+---------------+
| sec (GB4LZ...RB2A7)  | XLM      | 10010.0000000 |
+----------------------+----------+---------------+
```

**Comment by MikeFair** [comment]
I like the fact that it separates account boundaries now but this new format made a new confusion the other direction:
```
+-------------------------+----------+---------------+
| escrow (GB25P...IUJSF)  | USD      |     0.0000000 |
+-------------------------+----------+---------------+
|                         | USD      |  9080.0000000 |
+-------------------------+----------+---------------+
|                         | USD      |   105.0000000 |
+-------------------------+----------+---------------+
|                         | XLM      | 10009.9974300 |
+-------------------------+----------+---------------+
```

I do like the grouping and "open spaces" view to show that these things were the same; only crossing the account boundary was the confusing part.  

Within the same account, the currencies should group like they did, just not across the account boundaries.  Also, as you can see, this account holds three different USD currencies from three different issuers.   I don't know how/if I want to fix it because I appreciate the conciseness of the display; but I do find it unclear which USD came from which issuer which is something I'd like to see clearly because it matters.  (For the moment I can tell because I know roughly what balances belong to each issuer, but without that "secret knowledge" there'd be no way to distinguish them; perhaps ordering them alphabetically by the asset_issuer account or by nickname if they exist in the database?

If you'd like to test this account, it's:
GB25PA4Z5NF34WSL737ZE7VKBMBPNDJGJAAMHKYCDGYZ6QFPQLDIUJSF
on testnet I call it the "escrow" account.

**Comment by celrenheit** [comment]
For now I can add the issuer (something like `(GB25P...IUJSF)`) in the asset column.
